/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables;


import com.graduation.user.DefaultSchema;
import com.graduation.user.Indexes;
import com.graduation.user.Keys;
import com.graduation.user.tables.records.GraRoleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraRole extends TableImpl<GraRoleRecord> {

    private static final long serialVersionUID = 526257884;

    /**
     * The reference instance of <code>gra_role</code>
     */
    public static final GraRole GRA_ROLE = new GraRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GraRoleRecord> getRecordType() {
        return GraRoleRecord.class;
    }

    /**
     * The column <code>gra_role.id</code>.
     */
    public final TableField<GraRoleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gra_role.role_name</code>. 角色
     */
    public final TableField<GraRoleRecord, String> ROLE_NAME = createField("role_name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("角色", org.jooq.impl.SQLDataType.VARCHAR)), this, "角色");

    /**
     * The column <code>gra_role.ctime</code>. 创建时间
     */
    public final TableField<GraRoleRecord, Timestamp> CTIME = createField("ctime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>gra_role.mtime</code>. 修改时间
     */
    public final TableField<GraRoleRecord, Timestamp> MTIME = createField("mtime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * Create a <code>gra_role</code> table reference
     */
    public GraRole() {
        this(DSL.name("gra_role"), null);
    }

    /**
     * Create an aliased <code>gra_role</code> table reference
     */
    public GraRole(String alias) {
        this(DSL.name(alias), GRA_ROLE);
    }

    /**
     * Create an aliased <code>gra_role</code> table reference
     */
    public GraRole(Name alias) {
        this(alias, GRA_ROLE);
    }

    private GraRole(Name alias, Table<GraRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private GraRole(Name alias, Table<GraRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GraRole(Table<O> child, ForeignKey<O, GraRoleRecord> key) {
        super(child, key, GRA_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GRA_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GraRoleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GRA_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GraRoleRecord> getPrimaryKey() {
        return Keys.KEY_GRA_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GraRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<GraRoleRecord>>asList(Keys.KEY_GRA_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraRole as(String alias) {
        return new GraRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraRole as(Name alias) {
        return new GraRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GraRole rename(String name) {
        return new GraRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GraRole rename(Name name) {
        return new GraRole(name, null);
    }
}
