/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 学院表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraCollegeEntity implements Serializable {

    private static final long serialVersionUID = -1429763074;

    private Integer   id;
    private String    colName;
    private Integer   stuTotal;
    private Integer   teaTotal;
    private Timestamp ctime;
    private Timestamp mtime;

    public GraCollegeEntity() {}

    public GraCollegeEntity(GraCollegeEntity value) {
        this.id = value.id;
        this.colName = value.colName;
        this.stuTotal = value.stuTotal;
        this.teaTotal = value.teaTotal;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public GraCollegeEntity(
        Integer   id,
        String    colName,
        Integer   stuTotal,
        Integer   teaTotal,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.colName = colName;
        this.stuTotal = stuTotal;
        this.teaTotal = teaTotal;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getColName() {
        return this.colName;
    }

    public void setColName(String colName) {
        this.colName = colName;
    }

    public Integer getStuTotal() {
        return this.stuTotal;
    }

    public void setStuTotal(Integer stuTotal) {
        this.stuTotal = stuTotal;
    }

    public Integer getTeaTotal() {
        return this.teaTotal;
    }

    public void setTeaTotal(Integer teaTotal) {
        this.teaTotal = teaTotal;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraCollegeEntity (");

        sb.append(id);
        sb.append(", ").append(colName);
        sb.append(", ").append(stuTotal);
        sb.append(", ").append(teaTotal);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
