/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 专业表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraMajorEntity implements Serializable {

    private static final long serialVersionUID = 1090385768;

    private Integer   id;
    private String    majorName;
    private Integer   collegeId;
    private Timestamp ctime;
    private Timestamp mtime;

    public GraMajorEntity() {}

    public GraMajorEntity(GraMajorEntity value) {
        this.id = value.id;
        this.majorName = value.majorName;
        this.collegeId = value.collegeId;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public GraMajorEntity(
        Integer   id,
        String    majorName,
        Integer   collegeId,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.majorName = majorName;
        this.collegeId = collegeId;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMajorName() {
        return this.majorName;
    }

    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    public Integer getCollegeId() {
        return this.collegeId;
    }

    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraMajorEntity (");

        sb.append(id);
        sb.append(", ").append(majorName);
        sb.append(", ").append(collegeId);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
