/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraPermissionEntity implements Serializable {

    private static final long serialVersionUID = -2047272677;

    private Integer   id;
    private String    permission;
    private Integer   roleId;
    private String    roleName;
    private Timestamp ctime;
    private Timestamp mtime;

    public GraPermissionEntity() {}

    public GraPermissionEntity(GraPermissionEntity value) {
        this.id = value.id;
        this.permission = value.permission;
        this.roleId = value.roleId;
        this.roleName = value.roleName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public GraPermissionEntity(
        Integer   id,
        String    permission,
        Integer   roleId,
        String    roleName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.permission = permission;
        this.roleId = roleId;
        this.roleName = roleName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPermission() {
        return this.permission;
    }

    public void setPermission(String permission) {
        this.permission = permission;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraPermissionEntity (");

        sb.append(id);
        sb.append(", ").append(permission);
        sb.append(", ").append(roleId);
        sb.append(", ").append(roleName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
