/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraRoleEntity implements Serializable {

    private static final long serialVersionUID = -1544634665;

    private Integer   id;
    private String    roleName;
    private Timestamp ctime;
    private Timestamp mtime;

    public GraRoleEntity() {}

    public GraRoleEntity(GraRoleEntity value) {
        this.id = value.id;
        this.roleName = value.roleName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public GraRoleEntity(
        Integer   id,
        String    roleName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.roleName = roleName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraRoleEntity (");

        sb.append(id);
        sb.append(", ").append(roleName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
