/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 学生表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraStudentEntity implements Serializable {

    private static final long serialVersionUID = -1565934732;

    private Integer   id;
    private String    stuId;
    private String    stuPasswd;
    private String    stuName;
    private Integer   collegeId;
    private String    collegeName;
    private Integer   roleId;
    private String    roleName;
    private Timestamp ctime;
    private Timestamp mtime;

    public GraStudentEntity() {}

    public GraStudentEntity(GraStudentEntity value) {
        this.id = value.id;
        this.stuId = value.stuId;
        this.stuPasswd = value.stuPasswd;
        this.stuName = value.stuName;
        this.collegeId = value.collegeId;
        this.collegeName = value.collegeName;
        this.roleId = value.roleId;
        this.roleName = value.roleName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public GraStudentEntity(
        Integer   id,
        String    stuId,
        String    stuPasswd,
        String    stuName,
        Integer   collegeId,
        String    collegeName,
        Integer   roleId,
        String    roleName,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.stuId = stuId;
        this.stuPasswd = stuPasswd;
        this.stuName = stuName;
        this.collegeId = collegeId;
        this.collegeName = collegeName;
        this.roleId = roleId;
        this.roleName = roleName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStuId() {
        return this.stuId;
    }

    public void setStuId(String stuId) {
        this.stuId = stuId;
    }

    public String getStuPasswd() {
        return this.stuPasswd;
    }

    public void setStuPasswd(String stuPasswd) {
        this.stuPasswd = stuPasswd;
    }

    public String getStuName() {
        return this.stuName;
    }

    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    public Integer getCollegeId() {
        return this.collegeId;
    }

    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    public String getCollegeName() {
        return this.collegeName;
    }

    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraStudentEntity (");

        sb.append(id);
        sb.append(", ").append(stuId);
        sb.append(", ").append(stuPasswd);
        sb.append(", ").append(stuName);
        sb.append(", ").append(collegeId);
        sb.append(", ").append(collegeName);
        sb.append(", ").append(roleId);
        sb.append(", ").append(roleName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
