/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.daos;


import com.graduation.user.tables.GraCollege;
import com.graduation.user.tables.pojos.GraCollegeEntity;
import com.graduation.user.tables.records.GraCollegeRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 学院表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraCollegeEntityDao extends DAOImpl<GraCollegeRecord, GraCollegeEntity, Integer> {

    /**
     * Create a new GraCollegeEntityDao without any configuration
     */
    public GraCollegeEntityDao() {
        super(GraCollege.GRA_COLLEGE, GraCollegeEntity.class);
    }

    /**
     * Create a new GraCollegeEntityDao with an attached configuration
     */
    public GraCollegeEntityDao(Configuration configuration) {
        super(GraCollege.GRA_COLLEGE, GraCollegeEntity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(GraCollegeEntity object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<GraCollegeEntity> fetchById(Integer... values) {
        return fetch(GraCollege.GRA_COLLEGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public GraCollegeEntity fetchOneById(Integer value) {
        return fetchOne(GraCollege.GRA_COLLEGE.ID, value);
    }

    /**
     * Fetch records that have <code>col_name IN (values)</code>
     */
    public List<GraCollegeEntity> fetchByColName(String... values) {
        return fetch(GraCollege.GRA_COLLEGE.COL_NAME, values);
    }

    /**
     * Fetch records that have <code>stu_total IN (values)</code>
     */
    public List<GraCollegeEntity> fetchByStuTotal(Integer... values) {
        return fetch(GraCollege.GRA_COLLEGE.STU_TOTAL, values);
    }

    /**
     * Fetch records that have <code>tea_total IN (values)</code>
     */
    public List<GraCollegeEntity> fetchByTeaTotal(Integer... values) {
        return fetch(GraCollege.GRA_COLLEGE.TEA_TOTAL, values);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<GraCollegeEntity> fetchByCtime(Timestamp... values) {
        return fetch(GraCollege.GRA_COLLEGE.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<GraCollegeEntity> fetchByMtime(Timestamp... values) {
        return fetch(GraCollege.GRA_COLLEGE.MTIME, values);
    }
}
