/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.daos;


import com.graduation.user.tables.GraMajor;
import com.graduation.user.tables.pojos.GraMajorEntity;
import com.graduation.user.tables.records.GraMajorRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 专业表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraMajorEntityDao extends DAOImpl<GraMajorRecord, GraMajorEntity, Integer> {

    /**
     * Create a new GraMajorEntityDao without any configuration
     */
    public GraMajorEntityDao() {
        super(GraMajor.GRA_MAJOR, GraMajorEntity.class);
    }

    /**
     * Create a new GraMajorEntityDao with an attached configuration
     */
    public GraMajorEntityDao(Configuration configuration) {
        super(GraMajor.GRA_MAJOR, GraMajorEntity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(GraMajorEntity object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<GraMajorEntity> fetchById(Integer... values) {
        return fetch(GraMajor.GRA_MAJOR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public GraMajorEntity fetchOneById(Integer value) {
        return fetchOne(GraMajor.GRA_MAJOR.ID, value);
    }

    /**
     * Fetch records that have <code>major_name IN (values)</code>
     */
    public List<GraMajorEntity> fetchByMajorName(String... values) {
        return fetch(GraMajor.GRA_MAJOR.MAJOR_NAME, values);
    }

    /**
     * Fetch records that have <code>college_id IN (values)</code>
     */
    public List<GraMajorEntity> fetchByCollegeId(Integer... values) {
        return fetch(GraMajor.GRA_MAJOR.COLLEGE_ID, values);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<GraMajorEntity> fetchByCtime(Timestamp... values) {
        return fetch(GraMajor.GRA_MAJOR.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<GraMajorEntity> fetchByMtime(Timestamp... values) {
        return fetch(GraMajor.GRA_MAJOR.MTIME, values);
    }
}
