/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.daos;


import com.graduation.user.tables.GraRole;
import com.graduation.user.tables.pojos.GraRoleEntity;
import com.graduation.user.tables.records.GraRoleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraRoleEntityDao extends DAOImpl<GraRoleRecord, GraRoleEntity, Integer> {

    /**
     * Create a new GraRoleEntityDao without any configuration
     */
    public GraRoleEntityDao() {
        super(GraRole.GRA_ROLE, GraRoleEntity.class);
    }

    /**
     * Create a new GraRoleEntityDao with an attached configuration
     */
    public GraRoleEntityDao(Configuration configuration) {
        super(GraRole.GRA_ROLE, GraRoleEntity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(GraRoleEntity object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<GraRoleEntity> fetchById(Integer... values) {
        return fetch(GraRole.GRA_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public GraRoleEntity fetchOneById(Integer value) {
        return fetchOne(GraRole.GRA_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>role_name IN (values)</code>
     */
    public List<GraRoleEntity> fetchByRoleName(String... values) {
        return fetch(GraRole.GRA_ROLE.ROLE_NAME, values);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<GraRoleEntity> fetchByCtime(Timestamp... values) {
        return fetch(GraRole.GRA_ROLE.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<GraRoleEntity> fetchByMtime(Timestamp... values) {
        return fetch(GraRole.GRA_ROLE.MTIME, values);
    }
}
