/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.daos;


import com.graduation.user.tables.GraStudent;
import com.graduation.user.tables.pojos.GraStudentEntity;
import com.graduation.user.tables.records.GraStudentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 学生表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraStudentEntityDao extends DAOImpl<GraStudentRecord, GraStudentEntity, Integer> {

    /**
     * Create a new GraStudentEntityDao without any configuration
     */
    public GraStudentEntityDao() {
        super(GraStudent.GRA_STUDENT, GraStudentEntity.class);
    }

    /**
     * Create a new GraStudentEntityDao with an attached configuration
     */
    public GraStudentEntityDao(Configuration configuration) {
        super(GraStudent.GRA_STUDENT, GraStudentEntity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(GraStudentEntity object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<GraStudentEntity> fetchById(Integer... values) {
        return fetch(GraStudent.GRA_STUDENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public GraStudentEntity fetchOneById(Integer value) {
        return fetchOne(GraStudent.GRA_STUDENT.ID, value);
    }

    /**
     * Fetch records that have <code>stu_id IN (values)</code>
     */
    public List<GraStudentEntity> fetchByStuId(String... values) {
        return fetch(GraStudent.GRA_STUDENT.STU_ID, values);
    }

    /**
     * Fetch records that have <code>stu_passwd IN (values)</code>
     */
    public List<GraStudentEntity> fetchByStuPasswd(String... values) {
        return fetch(GraStudent.GRA_STUDENT.STU_PASSWD, values);
    }

    /**
     * Fetch records that have <code>stu_name IN (values)</code>
     */
    public List<GraStudentEntity> fetchByStuName(String... values) {
        return fetch(GraStudent.GRA_STUDENT.STU_NAME, values);
    }

    /**
     * Fetch records that have <code>college_id IN (values)</code>
     */
    public List<GraStudentEntity> fetchByCollegeId(Integer... values) {
        return fetch(GraStudent.GRA_STUDENT.COLLEGE_ID, values);
    }

    /**
     * Fetch records that have <code>college_name IN (values)</code>
     */
    public List<GraStudentEntity> fetchByCollegeName(String... values) {
        return fetch(GraStudent.GRA_STUDENT.COLLEGE_NAME, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<GraStudentEntity> fetchByRoleId(Integer... values) {
        return fetch(GraStudent.GRA_STUDENT.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>role_name IN (values)</code>
     */
    public List<GraStudentEntity> fetchByRoleName(String... values) {
        return fetch(GraStudent.GRA_STUDENT.ROLE_NAME, values);
    }

    /**
     * Fetch records that have <code>ctime IN (values)</code>
     */
    public List<GraStudentEntity> fetchByCtime(Timestamp... values) {
        return fetch(GraStudent.GRA_STUDENT.CTIME, values);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<GraStudentEntity> fetchByMtime(Timestamp... values) {
        return fetch(GraStudent.GRA_STUDENT.MTIME, values);
    }
}
