#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 981208
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/graduation?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8&serverTimezone=Asia/Shanghai

druid:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 981208
  url: jdbc:mysql://localhost:3306/graduation?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8&serverTimezone=Asia/Shanghai


server:
  port: 7001
