/*
 * This file is generated by jOOQ.
 */
package com.graduation.user;


import com.graduation.user.tables.GraCollege;
import com.graduation.user.tables.GraMajor;
import com.graduation.user.tables.GraPermission;
import com.graduation.user.tables.GraRole;
import com.graduation.user.tables.GraStudent;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GRA_COLLEGE_PRIMARY = Indexes0.GRA_COLLEGE_PRIMARY;
    public static final Index GRA_MAJOR_COL_ID = Indexes0.GRA_MAJOR_COL_ID;
    public static final Index GRA_MAJOR_PRIMARY = Indexes0.GRA_MAJOR_PRIMARY;
    public static final Index GRA_PERMISSION_PRIMARY = Indexes0.GRA_PERMISSION_PRIMARY;
    public static final Index GRA_PERMISSION_ROLE_ID = Indexes0.GRA_PERMISSION_ROLE_ID;
    public static final Index GRA_ROLE_PRIMARY = Indexes0.GRA_ROLE_PRIMARY;
    public static final Index GRA_STUDENT_COLLEGE_ID = Indexes0.GRA_STUDENT_COLLEGE_ID;
    public static final Index GRA_STUDENT_PRIMARY = Indexes0.GRA_STUDENT_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GRA_COLLEGE_PRIMARY = Internal.createIndex("PRIMARY", GraCollege.GRA_COLLEGE, new OrderField[] { GraCollege.GRA_COLLEGE.ID }, true);
        public static Index GRA_MAJOR_COL_ID = Internal.createIndex("col_id", GraMajor.GRA_MAJOR, new OrderField[] { GraMajor.GRA_MAJOR.COLLEGE_ID }, false);
        public static Index GRA_MAJOR_PRIMARY = Internal.createIndex("PRIMARY", GraMajor.GRA_MAJOR, new OrderField[] { GraMajor.GRA_MAJOR.ID }, true);
        public static Index GRA_PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", GraPermission.GRA_PERMISSION, new OrderField[] { GraPermission.GRA_PERMISSION.ID }, true);
        public static Index GRA_PERMISSION_ROLE_ID = Internal.createIndex("role_id", GraPermission.GRA_PERMISSION, new OrderField[] { GraPermission.GRA_PERMISSION.ROLE_ID }, false);
        public static Index GRA_ROLE_PRIMARY = Internal.createIndex("PRIMARY", GraRole.GRA_ROLE, new OrderField[] { GraRole.GRA_ROLE.ID }, true);
        public static Index GRA_STUDENT_COLLEGE_ID = Internal.createIndex("college_id", GraStudent.GRA_STUDENT, new OrderField[] { GraStudent.GRA_STUDENT.COLLEGE_ID }, false);
        public static Index GRA_STUDENT_PRIMARY = Internal.createIndex("PRIMARY", GraStudent.GRA_STUDENT, new OrderField[] { GraStudent.GRA_STUDENT.ID }, true);
    }
}
