/*
 * This file is generated by jOOQ.
 */
package com.graduation.user;


import com.graduation.user.tables.GraCollege;
import com.graduation.user.tables.GraMajor;
import com.graduation.user.tables.GraPermission;
import com.graduation.user.tables.GraRole;
import com.graduation.user.tables.GraStudent;
import com.graduation.user.tables.records.GraCollegeRecord;
import com.graduation.user.tables.records.GraMajorRecord;
import com.graduation.user.tables.records.GraPermissionRecord;
import com.graduation.user.tables.records.GraRoleRecord;
import com.graduation.user.tables.records.GraStudentRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<GraCollegeRecord, Integer> IDENTITY_GRA_COLLEGE = Identities0.IDENTITY_GRA_COLLEGE;
    public static final Identity<GraMajorRecord, Integer> IDENTITY_GRA_MAJOR = Identities0.IDENTITY_GRA_MAJOR;
    public static final Identity<GraPermissionRecord, Integer> IDENTITY_GRA_PERMISSION = Identities0.IDENTITY_GRA_PERMISSION;
    public static final Identity<GraRoleRecord, Integer> IDENTITY_GRA_ROLE = Identities0.IDENTITY_GRA_ROLE;
    public static final Identity<GraStudentRecord, Integer> IDENTITY_GRA_STUDENT = Identities0.IDENTITY_GRA_STUDENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GraCollegeRecord> KEY_GRA_COLLEGE_PRIMARY = UniqueKeys0.KEY_GRA_COLLEGE_PRIMARY;
    public static final UniqueKey<GraMajorRecord> KEY_GRA_MAJOR_PRIMARY = UniqueKeys0.KEY_GRA_MAJOR_PRIMARY;
    public static final UniqueKey<GraPermissionRecord> KEY_GRA_PERMISSION_PRIMARY = UniqueKeys0.KEY_GRA_PERMISSION_PRIMARY;
    public static final UniqueKey<GraRoleRecord> KEY_GRA_ROLE_PRIMARY = UniqueKeys0.KEY_GRA_ROLE_PRIMARY;
    public static final UniqueKey<GraStudentRecord> KEY_GRA_STUDENT_PRIMARY = UniqueKeys0.KEY_GRA_STUDENT_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GraMajorRecord, GraCollegeRecord> COL_ID = ForeignKeys0.COL_ID;
    public static final ForeignKey<GraPermissionRecord, GraRoleRecord> ROLE_ID = ForeignKeys0.ROLE_ID;
    public static final ForeignKey<GraStudentRecord, GraCollegeRecord> COLLEGE_ID = ForeignKeys0.COLLEGE_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<GraCollegeRecord, Integer> IDENTITY_GRA_COLLEGE = Internal.createIdentity(GraCollege.GRA_COLLEGE, GraCollege.GRA_COLLEGE.ID);
        public static Identity<GraMajorRecord, Integer> IDENTITY_GRA_MAJOR = Internal.createIdentity(GraMajor.GRA_MAJOR, GraMajor.GRA_MAJOR.ID);
        public static Identity<GraPermissionRecord, Integer> IDENTITY_GRA_PERMISSION = Internal.createIdentity(GraPermission.GRA_PERMISSION, GraPermission.GRA_PERMISSION.ID);
        public static Identity<GraRoleRecord, Integer> IDENTITY_GRA_ROLE = Internal.createIdentity(GraRole.GRA_ROLE, GraRole.GRA_ROLE.ID);
        public static Identity<GraStudentRecord, Integer> IDENTITY_GRA_STUDENT = Internal.createIdentity(GraStudent.GRA_STUDENT, GraStudent.GRA_STUDENT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<GraCollegeRecord> KEY_GRA_COLLEGE_PRIMARY = Internal.createUniqueKey(GraCollege.GRA_COLLEGE, "KEY_gra_college_PRIMARY", GraCollege.GRA_COLLEGE.ID);
        public static final UniqueKey<GraMajorRecord> KEY_GRA_MAJOR_PRIMARY = Internal.createUniqueKey(GraMajor.GRA_MAJOR, "KEY_gra_major_PRIMARY", GraMajor.GRA_MAJOR.ID);
        public static final UniqueKey<GraPermissionRecord> KEY_GRA_PERMISSION_PRIMARY = Internal.createUniqueKey(GraPermission.GRA_PERMISSION, "KEY_gra_permission_PRIMARY", GraPermission.GRA_PERMISSION.ID);
        public static final UniqueKey<GraRoleRecord> KEY_GRA_ROLE_PRIMARY = Internal.createUniqueKey(GraRole.GRA_ROLE, "KEY_gra_role_PRIMARY", GraRole.GRA_ROLE.ID);
        public static final UniqueKey<GraStudentRecord> KEY_GRA_STUDENT_PRIMARY = Internal.createUniqueKey(GraStudent.GRA_STUDENT, "KEY_gra_student_PRIMARY", GraStudent.GRA_STUDENT.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<GraMajorRecord, GraCollegeRecord> COL_ID = Internal.createForeignKey(com.graduation.user.Keys.KEY_GRA_COLLEGE_PRIMARY, GraMajor.GRA_MAJOR, "col_id", GraMajor.GRA_MAJOR.COLLEGE_ID);
        public static final ForeignKey<GraPermissionRecord, GraRoleRecord> ROLE_ID = Internal.createForeignKey(com.graduation.user.Keys.KEY_GRA_ROLE_PRIMARY, GraPermission.GRA_PERMISSION, "role_id", GraPermission.GRA_PERMISSION.ROLE_ID);
        public static final ForeignKey<GraStudentRecord, GraCollegeRecord> COLLEGE_ID = Internal.createForeignKey(com.graduation.user.Keys.KEY_GRA_COLLEGE_PRIMARY, GraStudent.GRA_STUDENT, "college_id", GraStudent.GRA_STUDENT.COLLEGE_ID);
    }
}
