/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.records;


import com.graduation.user.tables.GraCollege;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学院表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraCollegeRecord extends UpdatableRecordImpl<GraCollegeRecord> implements Record6<Integer, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1604678781;

    /**
     * Setter for <code>gra_college.id</code>. 学院id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gra_college.id</code>. 学院id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gra_college.col_name</code>. 学院
     */
    public void setColName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gra_college.col_name</code>. 学院
     */
    public String getColName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gra_college.stu_total</code>. 学生总数
     */
    public void setStuTotal(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gra_college.stu_total</code>. 学生总数
     */
    public Integer getStuTotal() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gra_college.tea_total</code>. 教师总数
     */
    public void setTeaTotal(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gra_college.tea_total</code>. 教师总数
     */
    public Integer getTeaTotal() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gra_college.ctime</code>. 创建时间
     */
    public void setCtime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>gra_college.ctime</code>. 创建时间
     */
    public Timestamp getCtime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>gra_college.mtime</code>. 修改时间
     */
    public void setMtime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>gra_college.mtime</code>. 修改时间
     */
    public Timestamp getMtime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GraCollege.GRA_COLLEGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GraCollege.GRA_COLLEGE.COL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GraCollege.GRA_COLLEGE.STU_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return GraCollege.GRA_COLLEGE.TEA_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return GraCollege.GRA_COLLEGE.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return GraCollege.GRA_COLLEGE.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getColName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStuTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTeaTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getColName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStuTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTeaTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraCollegeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraCollegeRecord value2(String value) {
        setColName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraCollegeRecord value3(Integer value) {
        setStuTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraCollegeRecord value4(Integer value) {
        setTeaTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraCollegeRecord value5(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraCollegeRecord value6(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraCollegeRecord values(Integer value1, String value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GraCollegeRecord
     */
    public GraCollegeRecord() {
        super(GraCollege.GRA_COLLEGE);
    }

    /**
     * Create a detached, initialised GraCollegeRecord
     */
    public GraCollegeRecord(Integer id, String colName, Integer stuTotal, Integer teaTotal, Timestamp ctime, Timestamp mtime) {
        super(GraCollege.GRA_COLLEGE);

        set(0, id);
        set(1, colName);
        set(2, stuTotal);
        set(3, teaTotal);
        set(4, ctime);
        set(5, mtime);
    }
}
