/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.records;


import com.graduation.user.tables.GraMajor;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 专业表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraMajorRecord extends UpdatableRecordImpl<GraMajorRecord> implements Record5<Integer, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -660137904;

    /**
     * Setter for <code>gra_major.id</code>. 自增id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gra_major.id</code>. 自增id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gra_major.major_name</code>. 专业
     */
    public void setMajorName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gra_major.major_name</code>. 专业
     */
    public String getMajorName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gra_major.college_id</code>. 学院
     */
    public void setCollegeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gra_major.college_id</code>. 学院
     */
    public Integer getCollegeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gra_major.ctime</code>. 创建时间
     */
    public void setCtime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>gra_major.ctime</code>. 创建时间
     */
    public Timestamp getCtime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>gra_major.mtime</code>. 修改时间
     */
    public void setMtime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>gra_major.mtime</code>. 修改时间
     */
    public Timestamp getMtime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GraMajor.GRA_MAJOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GraMajor.GRA_MAJOR.MAJOR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GraMajor.GRA_MAJOR.COLLEGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return GraMajor.GRA_MAJOR.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return GraMajor.GRA_MAJOR.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMajorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCollegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMajorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCollegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraMajorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraMajorRecord value2(String value) {
        setMajorName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraMajorRecord value3(Integer value) {
        setCollegeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraMajorRecord value4(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraMajorRecord value5(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraMajorRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GraMajorRecord
     */
    public GraMajorRecord() {
        super(GraMajor.GRA_MAJOR);
    }

    /**
     * Create a detached, initialised GraMajorRecord
     */
    public GraMajorRecord(Integer id, String majorName, Integer collegeId, Timestamp ctime, Timestamp mtime) {
        super(GraMajor.GRA_MAJOR);

        set(0, id);
        set(1, majorName);
        set(2, collegeId);
        set(3, ctime);
        set(4, mtime);
    }
}
