/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.records;


import com.graduation.user.tables.GraPermission;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraPermissionRecord extends UpdatableRecordImpl<GraPermissionRecord> implements Record6<Integer, String, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1226988971;

    /**
     * Setter for <code>gra_permission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gra_permission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gra_permission.permission</code>. 权限
     */
    public void setPermission(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gra_permission.permission</code>. 权限
     */
    public String getPermission() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gra_permission.role_id</code>. 用户角色
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gra_permission.role_id</code>. 用户角色
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gra_permission.role_name</code>. 角色名称
     */
    public void setRoleName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gra_permission.role_name</code>. 角色名称
     */
    public String getRoleName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gra_permission.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>gra_permission.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>gra_permission.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>gra_permission.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GraPermission.GRA_PERMISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GraPermission.GRA_PERMISSION.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GraPermission.GRA_PERMISSION.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GraPermission.GRA_PERMISSION.ROLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return GraPermission.GRA_PERMISSION.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return GraPermission.GRA_PERMISSION.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraPermissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraPermissionRecord value2(String value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraPermissionRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraPermissionRecord value4(String value) {
        setRoleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraPermissionRecord value5(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraPermissionRecord value6(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraPermissionRecord values(Integer value1, String value2, Integer value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GraPermissionRecord
     */
    public GraPermissionRecord() {
        super(GraPermission.GRA_PERMISSION);
    }

    /**
     * Create a detached, initialised GraPermissionRecord
     */
    public GraPermissionRecord(Integer id, String permission, Integer roleId, String roleName, Timestamp ctime, Timestamp mtime) {
        super(GraPermission.GRA_PERMISSION);

        set(0, id);
        set(1, permission);
        set(2, roleId);
        set(3, roleName);
        set(4, ctime);
        set(5, mtime);
    }
}
