/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.records;


import com.graduation.user.tables.GraRole;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraRoleRecord extends UpdatableRecordImpl<GraRoleRecord> implements Record4<Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1834667304;

    /**
     * Setter for <code>gra_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gra_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gra_role.role_name</code>. 角色
     */
    public void setRoleName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gra_role.role_name</code>. 角色
     */
    public String getRoleName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gra_role.ctime</code>. 创建时间
     */
    public void setCtime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>gra_role.ctime</code>. 创建时间
     */
    public Timestamp getCtime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>gra_role.mtime</code>. 修改时间
     */
    public void setMtime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>gra_role.mtime</code>. 修改时间
     */
    public Timestamp getMtime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GraRole.GRA_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GraRole.GRA_ROLE.ROLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return GraRole.GRA_ROLE.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return GraRole.GRA_ROLE.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraRoleRecord value2(String value) {
        setRoleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraRoleRecord value3(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraRoleRecord value4(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraRoleRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GraRoleRecord
     */
    public GraRoleRecord() {
        super(GraRole.GRA_ROLE);
    }

    /**
     * Create a detached, initialised GraRoleRecord
     */
    public GraRoleRecord(Integer id, String roleName, Timestamp ctime, Timestamp mtime) {
        super(GraRole.GRA_ROLE);

        set(0, id);
        set(1, roleName);
        set(2, ctime);
        set(3, mtime);
    }
}
