/*
 * This file is generated by jOOQ.
 */
package com.graduation.user.tables.records;


import com.graduation.user.tables.GraStudent;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学生表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraStudentRecord extends UpdatableRecordImpl<GraStudentRecord> implements Record10<Integer, String, String, String, Integer, String, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1395862109;

    /**
     * Setter for <code>gra_student.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gra_student.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gra_student.stu_id</code>. 学号
     */
    public void setStuId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gra_student.stu_id</code>. 学号
     */
    public String getStuId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gra_student.stu_passwd</code>. 密码
     */
    public void setStuPasswd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gra_student.stu_passwd</code>. 密码
     */
    public String getStuPasswd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gra_student.stu_name</code>. 姓名
     */
    public void setStuName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gra_student.stu_name</code>. 姓名
     */
    public String getStuName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gra_student.college_id</code>. 学院id
     */
    public void setCollegeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gra_student.college_id</code>. 学院id
     */
    public Integer getCollegeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gra_student.college_name</code>. 学生所在学院
     */
    public void setCollegeName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gra_student.college_name</code>. 学生所在学院
     */
    public String getCollegeName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gra_student.role_id</code>. 角色id
     */
    public void setRoleId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gra_student.role_id</code>. 角色id
     */
    public Integer getRoleId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gra_student.role_name</code>. 角色名称
     */
    public void setRoleName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gra_student.role_name</code>. 角色名称
     */
    public String getRoleName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gra_student.ctime</code>. 创建时间
     */
    public void setCtime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>gra_student.ctime</code>. 创建时间
     */
    public Timestamp getCtime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>gra_student.mtime</code>. 修改时间
     */
    public void setMtime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>gra_student.mtime</code>. 修改时间
     */
    public Timestamp getMtime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, Integer, String, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, Integer, String, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GraStudent.GRA_STUDENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GraStudent.GRA_STUDENT.STU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GraStudent.GRA_STUDENT.STU_PASSWD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GraStudent.GRA_STUDENT.STU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return GraStudent.GRA_STUDENT.COLLEGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return GraStudent.GRA_STUDENT.COLLEGE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return GraStudent.GRA_STUDENT.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return GraStudent.GRA_STUDENT.ROLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return GraStudent.GRA_STUDENT.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return GraStudent.GRA_STUDENT.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getStuPasswd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCollegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCollegeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStuPasswd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCollegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCollegeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value2(String value) {
        setStuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value3(String value) {
        setStuPasswd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value4(String value) {
        setStuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value5(Integer value) {
        setCollegeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value6(String value) {
        setCollegeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value7(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value8(String value) {
        setRoleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value9(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord value10(Timestamp value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GraStudentRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, Integer value7, String value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GraStudentRecord
     */
    public GraStudentRecord() {
        super(GraStudent.GRA_STUDENT);
    }

    /**
     * Create a detached, initialised GraStudentRecord
     */
    public GraStudentRecord(Integer id, String stuId, String stuPasswd, String stuName, Integer collegeId, String collegeName, Integer roleId, String roleName, Timestamp ctime, Timestamp mtime) {
        super(GraStudent.GRA_STUDENT);

        set(0, id);
        set(1, stuId);
        set(2, stuPasswd);
        set(3, stuName);
        set(4, collegeId);
        set(5, collegeName);
        set(6, roleId);
        set(7, roleName);
        set(8, ctime);
        set(9, mtime);
    }
}
